#############################################################################
# Makefile for building: HomeAutomationServer
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  HomeAutomationServer.pro
# Template: subdirs
# Command: "E:\Program Files (x86)\Qt\5.6\msvc2015\bin\qmake.exe" -spec win32-msvc2015 "CONFIG+=debug" -o Makefile HomeAutomationServer.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = "E:\Program Files (x86)\Qt\5.6\msvc2015\bin\qmake.exe"
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-HomeAutomation-Network \
		sub-HomeAutomation-Devices \
		sub-HomeAutomation-Services \
		sub-HomeAutomationServer


sub-HomeAutomation-Network-qmake_all:  FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	cd HomeAutomation-Network\ && $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && $(MAKE) -f Makefile qmake_all
sub-HomeAutomation-Network: FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile
sub-HomeAutomation-Network-make_first-ordered: FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-HomeAutomation-Network-make_first: FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-HomeAutomation-Network-all-ordered: FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-HomeAutomation-Network-all: FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-HomeAutomation-Network-clean-ordered: FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-HomeAutomation-Network-clean: FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-HomeAutomation-Network-distclean-ordered: FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-HomeAutomation-Network-distclean: FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-HomeAutomation-Network-install_subtargets-ordered: FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-HomeAutomation-Network-install_subtargets: FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-HomeAutomation-Network-uninstall_subtargets-ordered: FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-HomeAutomation-Network-uninstall_subtargets: FORCE
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-HomeAutomation-Devices-qmake_all: sub-HomeAutomation-Network-qmake_all FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	cd HomeAutomation-Devices\ && $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && $(MAKE) -f Makefile qmake_all
sub-HomeAutomation-Devices: FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile
sub-HomeAutomation-Devices-make_first-ordered: sub-HomeAutomation-Network-make_first-ordered  FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-HomeAutomation-Devices-make_first: FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-HomeAutomation-Devices-all-ordered: sub-HomeAutomation-Network-all-ordered  FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-HomeAutomation-Devices-all: FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-HomeAutomation-Devices-clean-ordered: sub-HomeAutomation-Network-clean-ordered  FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-HomeAutomation-Devices-clean: FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-HomeAutomation-Devices-distclean-ordered: sub-HomeAutomation-Network-distclean-ordered  FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-HomeAutomation-Devices-distclean: FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-HomeAutomation-Devices-install_subtargets-ordered: sub-HomeAutomation-Network-install_subtargets-ordered  FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-HomeAutomation-Devices-install_subtargets: FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-HomeAutomation-Devices-uninstall_subtargets-ordered: sub-HomeAutomation-Network-uninstall_subtargets-ordered  FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-HomeAutomation-Devices-uninstall_subtargets: FORCE
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-HomeAutomation-Services-qmake_all: sub-HomeAutomation-Devices-qmake_all FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	cd HomeAutomation-Services\ && $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && $(MAKE) -f Makefile qmake_all
sub-HomeAutomation-Services: FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile
sub-HomeAutomation-Services-make_first-ordered: sub-HomeAutomation-Devices-make_first-ordered  FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-HomeAutomation-Services-make_first: FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-HomeAutomation-Services-all-ordered: sub-HomeAutomation-Devices-all-ordered  FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-HomeAutomation-Services-all: FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-HomeAutomation-Services-clean-ordered: sub-HomeAutomation-Devices-clean-ordered  FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-HomeAutomation-Services-clean: FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-HomeAutomation-Services-distclean-ordered: sub-HomeAutomation-Devices-distclean-ordered  FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-HomeAutomation-Services-distclean: FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-HomeAutomation-Services-install_subtargets-ordered: sub-HomeAutomation-Devices-install_subtargets-ordered  FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-HomeAutomation-Services-install_subtargets: FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-HomeAutomation-Services-uninstall_subtargets-ordered: sub-HomeAutomation-Devices-uninstall_subtargets-ordered  FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-HomeAutomation-Services-uninstall_subtargets: FORCE
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-HomeAutomationServer-qmake_all: sub-HomeAutomation-Services-qmake_all FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	cd HomeAutomationServer\ && $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && $(MAKE) -f Makefile qmake_all
sub-HomeAutomationServer: sub-HomeAutomation-Network \
		sub-HomeAutomation-Devices \
		sub-HomeAutomation-Services FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile
sub-HomeAutomationServer-make_first-ordered: sub-HomeAutomation-Services-make_first-ordered  FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-HomeAutomationServer-make_first: sub-HomeAutomation-Network-make_first sub-HomeAutomation-Devices-make_first sub-HomeAutomation-Services-make_first FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-HomeAutomationServer-all-ordered: sub-HomeAutomation-Services-all-ordered  FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-HomeAutomationServer-all: sub-HomeAutomation-Network-all sub-HomeAutomation-Devices-all sub-HomeAutomation-Services-all FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-HomeAutomationServer-clean-ordered: sub-HomeAutomation-Services-clean-ordered  FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-HomeAutomationServer-clean: sub-HomeAutomation-Network-clean sub-HomeAutomation-Devices-clean sub-HomeAutomation-Services-clean FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-HomeAutomationServer-distclean-ordered: sub-HomeAutomation-Services-distclean-ordered  FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-HomeAutomationServer-distclean: sub-HomeAutomation-Network-distclean sub-HomeAutomation-Devices-distclean sub-HomeAutomation-Services-distclean FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-HomeAutomationServer-install_subtargets-ordered: sub-HomeAutomation-Services-install_subtargets-ordered  FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-HomeAutomationServer-install_subtargets: sub-HomeAutomation-Network-install_subtargets sub-HomeAutomation-Devices-install_subtargets sub-HomeAutomation-Services-install_subtargets FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-HomeAutomationServer-uninstall_subtargets-ordered: sub-HomeAutomation-Services-uninstall_subtargets-ordered  FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-HomeAutomationServer-uninstall_subtargets: sub-HomeAutomation-Network-uninstall_subtargets sub-HomeAutomation-Devices-uninstall_subtargets sub-HomeAutomation-Services-uninstall_subtargets FORCE
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: HomeAutomationServer.pro "E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\win32-msvc2015\qmake.conf" "E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\spec_pre.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\common\angle.conf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\common\msvc-base.conf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\common\msvc-desktop.conf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\qconfig.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_axbase.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_axserver.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_clucene_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_concurrent.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_core.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_core_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_dbus.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_designer.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_designer_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_gui.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_gui_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_help.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_help_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_multimedia.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_network.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_network_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_nfc.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_opengl.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_platformsupport_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_positioning.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_printsupport.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_qml.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_qml_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_qmltest.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_quick.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_quick_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_sensors.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_serialport.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_sql.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_sql_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_svg.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_svg_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_testlib.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_uitools.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_webchannel.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_websockets.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_widgets.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_winextras.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_xml.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_xml_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\qt_functions.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\qt_config.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\win32\qt_config.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\win32-msvc2015\qmake.conf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\spec_post.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\exclusive_builds.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\default_pre.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\win32\default_pre.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\resolve_config.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\exclusive_builds_post.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\default_post.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\win32\rtti.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\precompile_header.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\warn_on.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\win32\windows.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\testcase_targets.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\exceptions.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\yacc.prf" \
		"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\lex.prf" \
		HomeAutomationServer.pro
	$(QMAKE) -spec win32-msvc2015 "CONFIG+=debug" -o Makefile HomeAutomationServer.pro
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\spec_pre.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\common\angle.conf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\common\msvc-base.conf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\common\msvc-desktop.conf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\qconfig.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_axbase.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_axbase_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_axcontainer.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_axcontainer_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_axserver.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_axserver_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_bluetooth.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_bluetooth_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_bootstrap_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_clucene_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_concurrent.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_concurrent_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_core.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_core_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_dbus.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_dbus_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_designer.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_designer_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_designercomponents_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_gui.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_gui_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_help.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_help_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_multimedia.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_multimedia_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_multimediawidgets.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_multimediawidgets_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_network.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_network_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_nfc.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_nfc_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_opengl.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_opengl_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_openglextensions.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_openglextensions_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_platformsupport_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_positioning.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_positioning_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_printsupport.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_printsupport_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_qml.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_qml_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_qmldevtools_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_qmltest.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_qmltest_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_quick.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_quick_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_quickparticles_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_quickwidgets.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_quickwidgets_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_sensors.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_sensors_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_serialport.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_serialport_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_sql.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_sql_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_svg.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_svg_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_testlib.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_testlib_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_uiplugin.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_uitools.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_uitools_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_webchannel.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_webchannel_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_websockets.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_websockets_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_widgets.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_widgets_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_winextras.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_winextras_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_xml.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_xml_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_xmlpatterns.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_xmlpatterns_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\modules\qt_lib_zlib_private.pri":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\qt_functions.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\qt_config.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\win32\qt_config.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\win32-msvc2015\qmake.conf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\spec_post.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\exclusive_builds.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\default_pre.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\win32\default_pre.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\resolve_config.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\exclusive_builds_post.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\default_post.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\win32\rtti.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\precompile_header.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\warn_on.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\win32\windows.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\testcase_targets.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\exceptions.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\yacc.prf":
"E:\Program Files (x86)\Qt\5.6\msvc2015\mkspecs\features\lex.prf":
HomeAutomationServer.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2015 "CONFIG+=debug" -o Makefile HomeAutomationServer.pro

qmake_all: sub-HomeAutomation-Network-qmake_all sub-HomeAutomation-Devices-qmake_all sub-HomeAutomation-Services-qmake_all sub-HomeAutomationServer-qmake_all FORCE

make_first: sub-HomeAutomation-Network-make_first-ordered sub-HomeAutomation-Devices-make_first-ordered sub-HomeAutomation-Services-make_first-ordered sub-HomeAutomationServer-make_first-ordered  FORCE
all: sub-HomeAutomation-Network-all-ordered sub-HomeAutomation-Devices-all-ordered sub-HomeAutomation-Services-all-ordered sub-HomeAutomationServer-all-ordered  FORCE
clean: sub-HomeAutomation-Network-clean-ordered sub-HomeAutomation-Devices-clean-ordered sub-HomeAutomation-Services-clean-ordered sub-HomeAutomationServer-clean-ordered  FORCE
distclean: sub-HomeAutomation-Network-distclean-ordered sub-HomeAutomation-Devices-distclean-ordered sub-HomeAutomation-Services-distclean-ordered sub-HomeAutomationServer-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-HomeAutomation-Network-install_subtargets-ordered sub-HomeAutomation-Devices-install_subtargets-ordered sub-HomeAutomation-Services-install_subtargets-ordered sub-HomeAutomationServer-install_subtargets-ordered FORCE
uninstall_subtargets: sub-HomeAutomation-Network-uninstall_subtargets-ordered sub-HomeAutomation-Devices-uninstall_subtargets-ordered sub-HomeAutomation-Services-uninstall_subtargets-ordered sub-HomeAutomationServer-uninstall_subtargets-ordered FORCE

sub-HomeAutomation-Network-debug_ordered:
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-HomeAutomation-Devices-debug_ordered: sub-HomeAutomation-Network-debug_ordered 
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-HomeAutomation-Services-debug_ordered: sub-HomeAutomation-Devices-debug_ordered 
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-HomeAutomationServer-debug_ordered: sub-HomeAutomation-Services-debug_ordered 
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-HomeAutomation-Network-debug_ordered sub-HomeAutomation-Devices-debug_ordered sub-HomeAutomation-Services-debug_ordered sub-HomeAutomationServer-debug_ordered

sub-HomeAutomation-Network-release_ordered:
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-HomeAutomation-Devices-release_ordered: sub-HomeAutomation-Network-release_ordered 
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-HomeAutomation-Services-release_ordered: sub-HomeAutomation-Devices-release_ordered 
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-HomeAutomationServer-release_ordered: sub-HomeAutomation-Services-release_ordered 
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile release
release: sub-HomeAutomation-Network-release_ordered sub-HomeAutomation-Devices-release_ordered sub-HomeAutomation-Services-release_ordered sub-HomeAutomationServer-release_ordered

sub-HomeAutomation-Network-check_ordered:
	@if not exist HomeAutomation-Network\ mkdir HomeAutomation-Network\ & if not exist HomeAutomation-Network\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Network\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Network\HomeAutomation-Network.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-HomeAutomation-Devices-check_ordered: sub-HomeAutomation-Network-check_ordered 
	@if not exist HomeAutomation-Devices\ mkdir HomeAutomation-Devices\ & if not exist HomeAutomation-Devices\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Devices\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Devices\HomeAutomation-Devices.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-HomeAutomation-Services-check_ordered: sub-HomeAutomation-Devices-check_ordered 
	@if not exist HomeAutomation-Services\ mkdir HomeAutomation-Services\ & if not exist HomeAutomation-Services\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomation-Services\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomation-Services\HomeAutomation-Services.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-HomeAutomationServer-check_ordered: sub-HomeAutomation-Services-check_ordered 
	@if not exist HomeAutomationServer\ mkdir HomeAutomationServer\ & if not exist HomeAutomationServer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HomeAutomationServer\ && ( if not exist Makefile $(QMAKE) C:\Arbeiten\PROGRAMMIERUNG\C++\QtCreator_DefaultWorkspace\HomeAutomationServer\HomeAutomationServer\HomeAutomationServer.pro -spec win32-msvc2015 "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile check
check: sub-HomeAutomation-Network-check_ordered sub-HomeAutomation-Devices-check_ordered sub-HomeAutomation-Services-check_ordered sub-HomeAutomationServer-check_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

